/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBridgeToken } from "./IBridgeToken";
export type { IConnextCore } from "./IConnextCore";
export type { IERC165 } from "./IERC165";
export type { IXReceiver } from "./IXReceiver";
