name: Custom Workflow for Connext Monorepo

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly-87bc53fc6c874bd4c92d97ed180b949e3a36d78c

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Check Yarn version
        run: yarn --version

      - name: Yarn install
        run: yarn install

      - name: Update git submodule
        run: git submodule update --init

      - name: Forge install
        run: yarn workspace @connext/smart-contracts forge:install

      ## Env file containing RPCs for 'connectors' integration tests
      - name: "Create env file"
        run: |
          touch ./packages/deployments/contracts/.env
          echo MAINNET_RPC="${{ secrets.MAINNET_RPC }}" >> ./packages/deployments/contracts/.env
          echo SCROLL_RPC="${{ secrets.SCROLL_RPC }}" >> ./packages/deployments/contracts/.env
          echo SEPOLIA_RPC="${{ secrets.SEPOLIA_RPC }}" >> ./packages/deployments/contracts/.env
          echo TAIKO_RPC="${{ secrets.TAIKO_RPC }}" >> ./packages/deployments/contracts/.env
          echo CRONOS_RPC="${{ secrets.CRONOS_RPC }}" >> ./packages/deployments/contracts/.env
          cat ./packages/deployments/contracts/.env

      ## Run tests for 'connectors'
      - name: Yarn test
        run: cd packages/deployments/contracts && forge test --mc Connector
